[book]
authors = ["async-crashdump-debugging Members"]
language = "en"
multilingual = false
src = "."
title = "async-crashdump-debugging initiative"

[output.html]
no-section-label=true
git-repository-url="https://github.com/rust-lang/async-crashdump-debugging-initiative"
edit-url-template="https://github.com/rust-lang/async-crashdump-debugging-initiative/edit/master/{path}"
site-url="/async-crashdump-debugging-initiative/"

[output.html.fold]
enable = true
level = 0
